# Generated by Django 5.1.4 on 2025-01-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('genre', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=10, max_digits=10)),
                ('language', models.CharField(default='English', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
