# Generated by Django 5.1.4 on 2025-01-11 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_review_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
    ]
