# Generated by Django 5.1.4 on 2025-01-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
